#!/bin/bash
# Test Help Command Handler
#
# Function for displaying test.sh help information.

show_help() {
    echo "Lyra Test Runner (Cloud Agent Compatible)"
    echo ""
    echo "Usage: $0 [global-options] {run|check|kill|debug|env|help} [options] [args...]"
    echo ""
    echo "Commands:"
    echo "  run [pytest_args...]      Start test execution (background)"
    echo "  check [run_id]            Wait until tests are done and print result tail"
    echo "  kill [run_id|--all]       Force stop pytest process (or emergency kill/cleanup)"
    echo "  debug [run_id]            Show detailed debug info about test run"
    echo "  env                       Show environment detection info"
    echo ""
    echo "Global Options:"
    echo "  --json        Output in JSON format (machine-readable)"
    echo "  --quiet, -q   Suppress non-essential output"
    echo ""
    echo "Recommended Pattern (multiple concurrent runs supported):"
    echo "  make test TARGET=tests/foo.py   # Returns RUN_ID"
    echo "  make test TARGET=tests/bar.py   # Another RUN_ID"
    echo "  make test-check RUN_ID=<run_id_1>"
    echo "  make test-check RUN_ID=<run_id_2>"
    echo ""
    echo "Runtime selection (default: auto=container>venv):"
    echo "  --auto        Prefer container if running, otherwise venv"
    echo "  --container   Force container execution (requires running container)"
    echo "  --venv        Force local venv execution"
    echo "  --name NAME   Override container name (default: \$CONTAINER_NAME or 'proxy')"
    echo ""
    echo "Completion Detection (reliable across runtimes):"
    echo "  - Uses done/exit marker files, NOT pytest output parsing or PID detection"
    echo "  - Works reliably with uv wrappers and container runtime differences"
    echo "  - Each RUN_ID has a host-side manifest for independent tracking"
    echo ""
    echo "State:"
    echo "  Persists last runtime to: ${TEST_STATE_FILE}"
    echo "  Per-run manifest stored in: \${TEST_RESULT_DIR}/run_\${run_id}.env"
    echo "  So check/get/kill will target the same environment by default."
    echo ""
    echo "Test Layers:"
    echo "  L1 (Cloud Agent/CI): Unit + Integration tests only (default in cloud)"
    echo "  L2 (Local):          Unit + Integration tests (default locally)"
    echo "  L3 (E2E):            All tests including E2E"
    echo ""
    echo "Environment Variables:"
    echo "  LYRA_TEST_LAYER=e2e  Run E2E tests explicitly"
    echo "  LYRA_TEST_LAYER=all  Run all tests"
    echo "  LYRA_LOCAL=1         Force local mode (disable cloud agent detection)"
    echo ""
    echo "Cloud Agent Detection:"
    echo "  Automatically detects these cloud agent environments:"
    echo "  - Cursor Cloud Agent: CURSOR_CLOUD_AGENT, CURSOR_SESSION_ID"
    echo "  - Claude Code: CLAUDE_CODE"
    echo "  - GitHub Actions: GITHUB_ACTIONS=true"
    echo "  - GitLab CI: GITLAB_CI"
    echo "  - Generic CI: CI=true"
    echo ""
    echo "Container Detection:"
    echo "  - Automatically detects if running inside container"
    echo "  - Container detection: /.dockerenv, /run/.containerenv, HOSTNAME"
    echo "  - In any container: ML tests (test_ml_server.py) are enabled"
    echo "  - In ml container: ML API tests (TestMLServerAPI) are enabled"
    echo ""
    echo "Container Architecture:"
    echo "  - proxy: Main container (proxy server, no ML libs)"
    echo "  - ml: ML container (FastAPI + ML libs, GPU)"
    echo "  - ollama: LLM container (Ollama, GPU) - unit tests use mocks"
    echo "  - tor: Tor proxy container - unit tests use mocks"
    echo ""
    echo "Manual Override (via .env or environment):"
    echo "  LYRA_RUN_ML_TESTS=1      Enable ML tests even without libs"
    echo "  LYRA_RUN_ML_API_TESTS=1  Enable ML API tests even without FastAPI"
    echo "  LYRA_RUN_EXTRACTOR_TESTS=1  Enable extractor tests (HTML extraction only)"
    echo ""
    echo "Note: Tests run in WSL venv (.venv) by default, or in container if detected."
    echo ""
    echo "Exit Codes (standardized for AI agents):"
    echo "  0   (EXIT_SUCCESS)       All tests passed (done marker + exit=0)"
    echo "  20  (EXIT_TEST_FAILED)   One or more tests failed (done marker + exit!=0)"
    echo "  21  (EXIT_TEST_ERROR)    Test execution error"
    echo "  22  (EXIT_TEST_TIMEOUT)  Test timeout (check gave up waiting)"
    echo "  23  (EXIT_TEST_FATAL)    Fatal error detected (disk I/O, OOM patterns)"
    echo "  24  (EXIT_TEST_CRASHED)  Runner exited without done marker (unexpected crash)"
    echo "  25  (EXIT_TEST_CANCELLED) Test explicitly cancelled via kill command"
    echo "  12  (EXIT_NOT_RUNNING)   Container not running"
    echo ""
    echo "Check Status Detection Priority:"
    echo "  1. done_file exists -> DONE (read exit_file for exit code)"
    echo "  2. fatal error pattern in output -> FATAL_ERROR"
    echo "  3. runner PID alive -> RUNNING (continue polling)"
    echo "  4. runner PID dead + no done marker -> CRASHED"
    echo "  5. timeout reached -> TIMEOUT"
}

