"""
Lyra Crawler Module.

Provides URL fetching, robots.txt compliance, and sitemap parsing.
"""

from src.crawler.bfs import (
    BFSResult,
    DomainBFSCrawler,
    ExtractedLink,
    LinkExtractor,
    LinkType,
    explore_domain,
    extract_page_links,
    get_bfs_crawler,
)
from src.crawler.browser_archive import (
    BrowserArchiver,
    CDXJEntry,
    CDXJGenerator,
    HARGenerator,
    NetworkEventCollector,
    ResourceInfo,
    archive_browser_page,
    get_browser_archiver,
    url_to_surt,
)
from src.crawler.dns_policy import (
    DNSCacheEntry,
    DNSLeakType,
    DNSMetrics,
    DNSPolicyManager,
    DNSResolutionResult,
    DNSRoute,
    get_dns_policy_manager,
    get_socks_proxy_for_request,
)
from src.crawler.fetcher import (
    BrowserFetcher,
    FetchResult,
    HTTPFetcher,
    HumanBehavior,
    RateLimiter,
    TorController,
    fetch_url,
    get_tor_controller,
)
from src.crawler.robots import (
    RobotsChecker,
    RobotsManager,
    RobotsRule,
    SitemapEntry,
    SitemapParser,
    SitemapResult,
    check_robots_compliance,
    get_robots_manager,
    get_sitemap_urls,
)
from src.crawler.sec_fetch import (
    NavigationContext,
    SecFetchDest,
    SecFetchHeaders,
    SecFetchMode,
    SecFetchSite,
    generate_headers_for_direct_navigation,
    generate_headers_for_internal_link,
    generate_headers_for_serp_click,
    generate_sec_fetch_headers,
)
from src.crawler.session_transfer import (
    CookieData,
    SessionData,
    SessionTransferManager,
    TransferResult,
    capture_browser_session,
    get_session_transfer_manager,
    get_transfer_headers,
    invalidate_session,
    update_session,
)
from src.crawler.site_search import (
    DomainSearchStats,
    SearchTemplate,
    SiteSearchManager,
    SiteSearchResult,
    get_site_search_manager,
    get_site_search_stats,
    list_allowlisted_domains,
    site_search,
)
from src.crawler.wayback import (
    ContentAnalyzer,
    ContentDiff,
    Snapshot,
    TimelineEntry,
    WaybackBudgetManager,
    WaybackClient,
    WaybackExplorer,
    WaybackResult,
    check_content_modified,
    explore_wayback,
    get_archived_content,
    get_wayback_budget_manager,
    get_wayback_explorer,
)

__all__ = [
    # Fetcher
    "FetchResult",
    "HTTPFetcher",
    "BrowserFetcher",
    "HumanBehavior",
    "TorController",
    "RateLimiter",
    "fetch_url",
    "get_tor_controller",
    # Sec-Fetch Headers
    "SecFetchSite",
    "SecFetchMode",
    "SecFetchDest",
    "SecFetchHeaders",
    "NavigationContext",
    "generate_sec_fetch_headers",
    "generate_headers_for_serp_click",
    "generate_headers_for_direct_navigation",
    "generate_headers_for_internal_link",
    # Robots/Sitemap
    "RobotsChecker",
    "RobotsRule",
    "SitemapParser",
    "SitemapEntry",
    "SitemapResult",
    "RobotsManager",
    "get_robots_manager",
    "check_robots_compliance",
    "get_sitemap_urls",
    # BFS
    "LinkType",
    "ExtractedLink",
    "BFSResult",
    "LinkExtractor",
    "DomainBFSCrawler",
    "get_bfs_crawler",
    "explore_domain",
    "extract_page_links",
    # Site Search
    "SearchTemplate",
    "SiteSearchResult",
    "DomainSearchStats",
    "SiteSearchManager",
    "get_site_search_manager",
    "site_search",
    "get_site_search_stats",
    "list_allowlisted_domains",
    # Wayback
    "Snapshot",
    "ContentDiff",
    "TimelineEntry",
    "WaybackResult",
    "WaybackClient",
    "ContentAnalyzer",
    "WaybackExplorer",
    "WaybackBudgetManager",
    "get_wayback_explorer",
    "get_wayback_budget_manager",
    "explore_wayback",
    "get_archived_content",
    "check_content_modified",
    # Session Transfer (ADR-0006)
    "CookieData",
    "SessionData",
    "TransferResult",
    "SessionTransferManager",
    "get_session_transfer_manager",
    "capture_browser_session",
    "get_transfer_headers",
    "update_session",
    "invalidate_session",
    # Browser Archive (ADR-0006)
    "ResourceInfo",
    "CDXJEntry",
    "NetworkEventCollector",
    "HARGenerator",
    "CDXJGenerator",
    "BrowserArchiver",
    "get_browser_archiver",
    "archive_browser_page",
    "url_to_surt",
    # DNS Policy (ADR-0006)
    "DNSRoute",
    "DNSLeakType",
    "DNSCacheEntry",
    "DNSResolutionResult",
    "DNSMetrics",
    "DNSPolicyManager",
    "get_dns_policy_manager",
    "get_socks_proxy_for_request",
]
