#!/bin/bash
# Chrome Help Functions
#
# Functions for displaying help information.

show_help() {
    local num_workers="${NUM_WORKERS:-2}"
    local base_port="${CHROME_BASE_PORT:-9222}"
    
    echo "Lyra Chrome Manager - Dynamic Worker Pool"
    echo ""
    echo "Usage: $0 [global-options] {status|start|start-worker|stop|restart|diagnose|fix} [args]"
    echo ""
    echo "Worker Pool:"
    echo "  Lyra uses a pool of Chrome instances, one per worker."
    echo "  Workers: $num_workers (from config/settings.yaml)"
    echo "  Ports: $base_port-$((base_port + num_workers - 1))"
    echo ""
    echo "Commands:"
    echo "  status          Show status of all Chrome workers (default)"
    echo "  start           Start Chrome for all workers"
    echo "  start-worker N  Start Chrome for a specific worker (N = worker ID, 0-indexed)"
    echo "  stop            Stop all Chrome instances"
    echo "  restart         Restart all Chrome instances"
    echo "  diagnose        Diagnose all workers (or: diagnose <port> for specific port)"
    echo "  fix             Auto-generate fix commands for WSL2 mirrored networking"
    echo ""
    echo "Global Options:"
    echo "  --json        Output in JSON format (machine-readable)"
    echo "  --quiet, -q   Suppress non-essential output"
    echo ""
    echo "Examples:"
    echo "  make chrome              # Show pool status"
    echo "  make chrome-start        # Start all Chrome workers"
    echo "  make chrome-stop         # Stop all Chrome workers"
    echo "  make chrome-diagnose     # Diagnose all workers"
    echo "  ./scripts/chrome.sh diagnose 9223  # Diagnose specific port"
    echo ""
    echo "Exit Codes:"
    echo "  0   (EXIT_SUCCESS)   All Chrome workers are ready"
    echo "  13  (EXIT_NOT_READY) Some Chrome workers not responding"
    echo "  31  (EXIT_NETWORK)   Network/connection error"
    echo ""
    echo "Each worker uses a separate profile (Lyra-00, Lyra-01, ...)"
    echo "so they won't interfere with each other or normal browsing."
    echo ""
    echo "WSL2 Note:"
    echo "  WSL2 requires mirrored networking mode for localhost access."
    echo "  Run 'make doctor-chrome-fix' if connection fails after WSL2 update."
}

